name: React CI

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: react-portfolio-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build React Application
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::293033346072:role/GitHubActionsECRRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.run_number }} .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.run_number }} \
          293033346072.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          docker push 293033346072.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Update ECS Service (Force New Deployment)
        run: |
          aws ecs update-service \
            --cluster react-portfolio-cluster \
            --service react-portfolio-task-service-mo91o9se \
            --force-new-deployment \
            --region ap-south-1